import './test-utils.js';
import './utils.test.js';
import './gltf.test.js';
import './viewer.test.js';
import './package.test.js';
import './instructions.test.js';
import './main-import.test.js';
import './syntax.test.js';
import './init-order.test.js';
import './state.test.js';
import './finish.test.js';
import './html.test.js';
import './url.test.js';
import { run } from './test-utils.js';
await run();
