import './test-utils.js';
import './utils.test.js';
import './gltf.test.js';
import './viewer.test.js';
import './importmap.test.js';
import './instructions.test.js';
import './syntax.test.js';
import './init-order.test.js';
import { run } from './test-utils.js';
await run();
